# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='creater',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='currency',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name=b'Company Name'),
        ),
    ]
