# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reminder', '0002_auto_20160318_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='create_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ship_date',
            field=models.DateField(null=True),
        ),
    ]
