# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reminder', '0003_auto_20160318_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='creater',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='currency',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.CharField(max_length=200, null=True, verbose_name=b'Company Name'),
        ),
    ]
