# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reminder', '0006_orders_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
