# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reminder', '0007_auto_20160403_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pay_term',
            field=models.CharField(max_length=200, null=True, verbose_name=b'Payment Term'),
        ),
    ]
