# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reminder', '0008_orders_pay_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='updater',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
